services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bus-statistics'
      - 'POSTGRES_USER=attacktive'
      - 'POSTGRES_PASSWORD=attacktive'
    ports:
      - '5432:5432'
