spring:
  application:
    name: 'bus-statistics'
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/bus-statistics'
    username: 'attacktive'
    password: 'attacktive'

app:
  service-key: "${SERVICE_KEY:}"
  bus-route-id: "${BUS_ROUTE_ID:}"
  st-id: "${ST_ID:}"
  schedule-cron-expression: "${SCHEDULE_CRON_EXPRESSION:0 * 8,9 * * ?}"
